package es.upm.dit.gsi.shanks.devices;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Splitter2.java
//  @ Date : 03/10/2011
//  @ Author : Daniel Lara
//
//




public class Splitter2 extends Splitter {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2296788632133739442L;

	public Splitter2(String id, int status, int temperature, int type) {
		super(id, status, temperature, type);
	}
}
