package es.upm.dit.gsi.shanks.model.device.ftth;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Splitter1.java
//  @ Date : 03/10/2011
//  @ Author : Daniel Lara
//
//

public class Splitter1 extends Splitter {

    /**
	 * 
	 */
    private static final long serialVersionUID = -7692959076564342643L;

    public Splitter1(String id, int status, int temperature, int type) {
        super(id, status, temperature, type);
    }

}
