package es.upm.dit.gsi.shanks.hackerhan.agent;

import es.upm.dit.gsi.shanks.ShanksSimulation;
import es.upm.dit.gsi.shanks.agent.SimpleShanksAgent;

/**
 * User agent represents a single user of Internet. The user consume services
 * on the web by acceding to them. This action will be simulated as a poissonian 
 * behavior over time.
 * 
 * Traffic generated by users conceal malicious access from hackers. 
 *  
 * @author Danny
 *
 */
public class User extends SimpleShanksAgent{

	public User(String id) {
		super(id);
	}

	@Override
	public void checkMail() {
		// TODO probably the user agent doesn't need this method. Unless 
		// the consume service behavior has been modelated as a mail 
		// conversation. 
	}

	@Override
	public void executeReasoningCycle(ShanksSimulation simulation) {
		// TODO Make randomly access to Internet services. Modelate it as a 
		// poissonian behavior 
	}
	private static final long serialVersionUID = 411280212631640801L;
}
