package es.upm.dit.gsi.shanks;
//package Simulacion;
//
//import java.awt.Color;
//import java.awt.Graphics;
//import java.awt.Graphics2D;
//import java.util.ArrayList;
//import java.util.List;
//import java.util.logging.Logger;
//
//
//import sim.engine.SimState;
//import sim.engine.Steppable;
//import sim.portrayal.DrawInfo2D;
//import sim.portrayal.SimplePortrayal2D;
//
////
////
////  Generated by StarUML(tm) Java Add-In
////
////  @ Project : SE4ND
////  @ File Name : Agente.java
////  @ Date : 20/10/2011
////  @ Author : Daniel Lara
////
////
//
//
//public class Agente extends SimplePortrayal2D implements Steppable{
//
//	private static final long serialVersionUID = -7448202235281457216L;
//	public static Scenarios scenario;
//	public List<Device> faildevices = new ArrayList<Device>();
//	public List<Device> totaldevice = new ArrayList<Device>();
//	
//	
//	public Agente(Scenarios scenario){
//		this.scenario = scenario;
//	}
//	
//	//Get the devices from scenario
//	public List<Device> getDeviceFromScenario(){
//		return Model.ftth;
//	}
//	
//	
//	//Draw the agent in the simulation window
//	public void draw(Object object, Graphics2D graphics, DrawInfo2D info){
//		
//		final double width = 20; 
//		final double height = 20;
//		final int x = (int) (info.draw.x - width / 2.0);
//		final int y = (int) (info.draw.y - height / 2.0);
//		final int w = (int) (width);
//		final int h = (int) (height);
//
//		graphics.fillOval(x, y, w, h);
//		graphics.setColor(Color.black);
//		graphics.drawString("Agente", x - 3, y);
//	}
//	
//	
//	// Get all the device that are broken
//	public List<Device> getFailureDevice(){
//		
//		totaldevice = getDeviceFromScenario();
//		System.out.println("NUMERO DEVICES EN ESCENARIO : " + totaldevice.size());
//		System.out.println("DEVICES " + totaldevice.toString());
//		
//		//Make a list with the broken devices
//		for(int i=0; i < totaldevice.size(); i++){
//			if(totaldevice.get(i).getStatus() == 1){
//				faildevices.add(totaldevice.get(i));
//			}
//		}
//		
//		if(faildevices.isEmpty()){
//			System.out.println("TODO CORRECTO");
//		}else{
//			for(int j = 0; j < faildevices.size(); j++){
//				System.out.println("FALLO EN: " + faildevices.get(j).getID());
//			}
//			
//		}
//		return faildevices;
//	}
//	
//	
//	//Repair all device putting their status at HEALTHY_STATUS
//	private void repairAllDevice(){
//		for(Device d : this.faildevices){
//			d.setStatus(Definitions.HEALTHY_STATUS);
//		}
//		faildevices.clear();
//	}
//	
//	
//	//The actions done by the agent for each step
//	public void step(SimState state) {
//		repairAllDevice();
//		System.out.println("NUEVA PRUEBA");
//		Model model = (Model)state;
//		Model.setBrokenStatus();
//		System.out.println("");
//		getFailureDevice();
//     	System.out.println(" ");
//     	System.out.println(" "); 	
//     	System.out.println("DEVICE CLEAR: " + faildevices.toString());
//	}
//
//}
