package es.upm.dit.gsi.shanks;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Splitter1.java
//  @ Date : 03/10/2011
//  @ Author : Daniel Lara
//
//




public class Splitter1 extends Splitter {

	public Splitter1(String id, int status, int temperature, int type) {
		super(id, status, temperature, type);
	}
	
	
}
